controller_list:
  - name: fake_dofbot_controller
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
initial:  # Define initial robot poses.
  - group: dofbot
    pose: up